### ISSUE TITLE
Pulling down the Data

### ISSUE THREAD

**Issue by stevenagl12** [mwritescode/endobayes#1]
The link that you have posted to get the data is broken. Is there another source for it, or maybe another way to get that data?

**Comment by mwritescode** [comment]
Hello!
As stated in the readme, the data is not mine. It was collected by Shani Cohen from Ariel University and she gave consent for me to use it for this univerity project only. I do not own the data nor host it myself anywhere else, so if the original link to her work is broken I'm sorry but I can't help you. You could maybe try to contact her yourself and ask for access tho, her github account should still be visibile from the readme.
Hope this cleared things up and thanks for showing interest in this project :)
